version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=Zlolka
      - POSTGRES_PASSWORD=aklolz
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis
    volumes:
      - redis_data:/data
  celery:
    build:
      context: .
      dockerfile: celery.Dockerfile
    env_file:
      - ./.env.dev
    volumes:
      - .:/celery_sample
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
      - celery
    volumes:
      - .:/celery_sample
volumes:
  postgres_data:
  redis_data:
