version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=Zlolka
      - POSTGRES_PASSWORD=aklolz
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
volumes:
  postgres_data:
